default: &default
  adapter: postgresql
  encoding: unicode
  username: pgadmin
  password: pgadmin
  host: localhost
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: doctor_system_development

test:
  <<: *default
  database: doctor_system_test

production:
  <<: *default
  database: appgaffe_production
  username: appgaffe
  password: <%= ENV['APPGAFFE_DATABASE_PASSWORD'] %>

